/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cell: typeof import('./src/components/Cell/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ErrorPage: typeof import('./src/components/ErrorPage/index.vue')['default']
    MycTable: typeof import('./src/components/MycTable.vue')['default']
    OrgTree: typeof import('./src/components/OrgTree.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    PageSearch: typeof import('./src/components/PageSearch.vue')['default']
    PageTable: typeof import('./src/components/PageTable.vue')['default']
    RightDrawer: typeof import('./src/components/RightDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/SelectPerson/selectBox.vue')['default']
    SelectCode: typeof import('./src/components/SelectCode.vue')['default']
    SelectOrg: typeof import('./src/components/SelectOrg.vue')['default']
    SelectPerson: typeof import('./src/components/SelectPerson.vue')['default']
    SelectResult: typeof import('./src/components/SelectPerson/selectResult.vue')['default']
    SelectRole: typeof import('./src/components/SelectRole.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
